name       : perl-digest-sha1
version    : '2.13'
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/G/GA/GAAS/Digest-SHA1-2.13.tar.gz : 68c1dac2187421f0eb7abf71452a06f190181b8fc4b28ededf5b90296fb943cc
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl interface to the SHA-1 algorithm
description: |
    The Digest::SHA1 module allows you to use the NIST SHA-1 message digest algorithm from within Perl programs. The algorithm takes as input a message of arbitrary length and produces as output a 160-bit fingerprint or message digest of the input.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
